# Generated by Django 2.1.7 on 2019-02-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190226_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo_electronico',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
