# Generated by Django 2.1.7 on 2019-02-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('correo_electronico', models.CharField(max_length=254, unique=True)),
                ('contrasena', models.TextField()),
            ],
        ),
    ]
